[package]
name = "concurrent_lru"
version = "0.1.0"
authors = ["zhongjn <zhongjn0@foxmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.5.2"

[dev-dependencies]
rand = "0.8.3"